name: Prettier
description: Check that files are formatted with Prettier.

inputs:
  parser:
    required: true
    description: "Which parser to use."
  paths:
    required: false
    description: "Paths to check target: [files|dirs|globs]"
  prettier-version:
    default: "2.5.1"
    required: false
    description: "The Prettier version."
  cache:
    default: "true"
    required: false
    description: "The flag to enable/disable cache. Specify false, if you wish disabling cache."

runs:
  using: composite

  steps:
    - name: Create cache parameter
      shell: bash
      id: cache-param
      if: ${{ inputs.cache == 'true' }}
      env:
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}
        PRETTIER_VERSION: ${{ inputs.prettier-version }}
      run: |
        cache_key="${RUNNER_OS}-${RUNNER_ARCH}-node-$(node --version)-$(date "+%Y-%m")-version-${PRETTIER_VERSION}"
        echo "::set-output name=cache-key::${cache_key}"
        echo "::set-output name=cache-dir::$(npm config get cache)"

    - name: Cache
      uses: actions/cache@v2
      if: ${{ inputs.cache == 'true' }}
      with:
        path: ${{ steps.cache-param.outputs.cache-dir }}
        key: ${{ steps.cache-param.outputs.cache-key }}

    - name: Install
      shell: bash
      env:
        PRETTIER_VERSION: ${{ inputs.prettier-version }}
      run: |
        npm install prettier@"${PRETTIER_VERSION}"

    - name: Display version
      shell: bash
      run: |
        npx prettier --version

    - name: Create default paths from parser
      shell: bash
      id: default-paths
      env:
        PARSER: ${{ inputs.parser }}
        PATHS: ${{ inputs.paths }}
      run: |
        if [[ "${PATHS}" != "" ]]; then
          echo "::set-output name=paths::${PATHS}"
          exit 0
        fi
        case "${PARSER}" in
          "yaml" ) echo '::set-output name=paths::**/*.y*ml' ;;
          "markdown" ) echo '::set-output name=paths::**/*.md' ;;
          * ) echo 'error: undefined paths'; exit 1 ;;
        esac

    - name: Run prettier
      shell: bash
      env:
        PARSER: ${{ inputs.parser }}
        PATHS: ${{ steps.default-paths.outputs.paths }}
      run: |
        IFS=$' ' read -a path_array <<< $(printenv PATHS)
        npx prettier --parser="${PARSER}" --check "${path_array[@]}"

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "align-left"
  color: "green"
