name: Prettier
description: Format code with Prettier.

inputs:
  parser:
    required: true
    description: "Which parser to use."
  paths:
    required: false
    description: "Paths to format target: [file/dir/glob ...]"

runs:
  using: composite

  steps:
    - name: Install
      shell: bash
      run: |
        sudo npm install -g prettier

    - name: Display version
      shell: bash
      run: |
        prettier --version

    - name: Create default paths from parser
      shell: bash
      id: default-paths
      env:
        PARSER: ${{ inputs.parser }}
        PATHS: ${{ inputs.paths }}
      run: |
        if [[ "${PATHS}" != "" ]]; then
          echo "::set-output name=paths::${PATHS}"
          exit 0
        fi
        case "${PARSER}" in
          "markdown" ) echo '::set-output name=paths::**/*.md' ;;
          * ) echo '::set-output name=paths::.' ;;
        esac

    - name: Run prettier
      shell: bash
      env:
        PARSER: ${{ inputs.parser }}
        PATHS: ${{ steps.default-paths.outputs.paths }}
      run: |
        prettier --parser="${PARSER}" --check "${PATHS}"

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "align-left"
  color: "green"
