name: Lint Markdown
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/lint-markdown.yml"
  pull_request:
    paths:
      - "**.md"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    name: Lint by markdownlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Display markdownlint
        run: markdownlint --version
      - name: Run markdownlint
        run: markdownlint --dot --config .markdownlint.yml '**/*.md'

  prettier:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prettier
        uses: tmknom/prettier-action@v0.3.0
        with:
          parser: "markdown"
