name: Test
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "action.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FIXTURES: ".github/fixtures"

jobs:
  minimal:
    name: Minimal
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test default paths with markdown
        uses: ./
        with:
          parser: "markdown"
      - name: Test default paths with yaml
        uses: ./
        with:
          parser: "yaml"

  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test valid markdown
        uses: ./
        with:
          parser: "markdown"
          paths: "${{ env.FIXTURES }}/valid_basic_md.txt"
      - name: Test invalid markdown
        uses: ./
        id: invalid-markdown
        continue-on-error: true
        with:
          parser: "markdown"
          paths: "${{ env.FIXTURES }}/invalid_basic_md.txt"
      - name: Verify for test invalid markdown
        env:
          OUTCOME: ${{ steps.invalid-markdown.outcome }}
        run: |
          if [[ "${OUTCOME}" != "failure" ]]; then
            exit 1
          fi

  yaml:
    name: YAML
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test valid yaml
        uses: ./
        with:
          parser: "yaml"
          paths: "action.yml"

  prettier-version:
    name: Prettier version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test to specified Prettier version
        uses: ./
        with:
          parser: "yaml"
          prettier-version: "2.5.0"

  paths:
    name: Multiple paths
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test multiple paths
        uses: ./
        with:
          parser: "markdown"
          paths: "${{ env.FIXTURES }}/valid_basic_md.txt ${{ env.FIXTURES }}/valid_alternative_md.txt"
