name: Test
on:
  push:
    branches:
      - test-composite-action
  pull_request:
    paths:
      - "action.yml"
      - ".github/workflows/test.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FIXTURES_PATH: ".github/fixtures"

jobs:
  test:
    name: Composite Action
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test default paths with markdown
        uses: ./
        with:
          parser: "markdown"
      - name: Test default paths with yaml
        uses: ./
        with:
          parser: "yaml"
      - name: Test valid markdown
        uses: ./
        with:
          parser: "markdown"
          paths: "${{ env.FIXTURES_PATH }}/valid_md.txt"
      - name: Test valid yaml
        uses: ./
        with:
          parser: "yaml"
          paths: "action.yml"
